app/users/forms/userforms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, PasswordField
from flask_pagedown.fields import PageDownField
from wtforms.validators import Length, Required
from wtforms import ValidationError


class EditForm(FlaskForm):
    name = StringField('Nom', validators=[Length(1,128)])
    about = PageDownField('À propos')
    location = StringField('Emplacement', validators=[Length(1,128)])
    password = PasswordField('Confirmez votre mot de passe', validators=[Required('Veuillez entrer un mot de passe.')])
    submit = SubmitField('Modifier mes informations')

app/users/__init__.py
from flask import Blueprint

users = Blueprint('users', __name__)

from . import views

app/users/views.py
from . import users
from app.models import User
from flask import render_template, abort, flash, redirect, url_for
from flask_login import current_user, login_required
from decorators import privileges_required
from .forms.userforms import EditForm
from app.models import User, Article
from app import db, POSTS_PER_PAGE


@users.route('/<username>')
@users.route('/<username>/<int:page>')
@login_required
def user(username, page=1):
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    posts = Article.query.filter(Article.collaborators.contains(user)).order_by(Article.timestamp.desc()).paginate(page, POSTS_PER_PAGE, False)
    return render_template('users/user.html', user=user, user_isadmin=user.is_administrator(), posts=posts)

@users.route('/<username>/edit', methods=['GET', 'POST'])
def edit(username):
    user = User.query.filter_by(username=username).first()
    if user != current_user:
        abort(403)
    form = EditForm(obj=user)

    if form.validate_on_submit():
        if user.check_password(form.password.data):
            user.name = form.name.data
            user.location = form.location.data
            user.about = form.about.data
            db.session.commit()
            flash('Compte modifié.', 'info')
            return redirect(url_for('users.user', username=user.username))
        flash('Mot de passe invalide.', 'warning')
    return render_template('users/edit.html', user=user, form=form)

app/templates/users/edit.html
{%- extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}CvMS - {{ user.username }} - Modifier mon compte{% endblock %}

{% block contents %}
{{super()}}
<div class="page-header"><h1>{{ user.username }} - Modifier mon compte</h1></div>
<div class="panel panel-default col-md-10 col-md-offset-1">
    <form class="form" method="post" role="form">
        {{ form.csrf_token }}
        {{ wtf.form_field(form.name) }}
        {{ wtf.form_field(form.location) }}
        <div class="form-group ">
            <label class="control-label" for="location">À propos</label>
            <a href="http://commonmark.org/help/" target="_blank" class="pull-right">Aide pour la mise en forme</a>
            {{ form.about(only_input=True, rows=10, style="width:100%;") }}
            <a href="#preview" target="_blank" class="pull-right" data-toggle="collapse">Prévisualiser</a>
            <div id="preview" class="collapse">
                {{ form.about(only_preview=True) }}
            </div>
        </div>
        {{ wtf.form_field(form.password) }}
        {{ wtf.form_field(form.submit) }}
    </form>
</div>
{%- endblock %}

{% block scripts %}
{{super()}}
{{ pagedown.include_pagedown() }}
{% endblock %}

app/templates/users/user.html
{%- extends "base.html" %}
{%- from "macros.html" import show_posts with context %}
{% from "bootstrap/pagination.html" import render_pagination %}

{% block title %}CvMS - {{ user.username }}{% endblock %}

{% block contents %}
{{super()}}
<div class="page-header"><h1>{{ user.username }}</h1></div>
<div class="panel panel-default col-md-10 col-md-offset-1">
    {% if current_user is equalto user %}
    <a href="{{ url_for('users.edit', username=current_user.username) }}" class="btn btn-primary pull-right">Modifier</a>
    {% endif %}
    {% if user_isadmin %}
    <a href="{{ url_for('admin.index') }}" class="btn btn-primary pull-right">Administration</a>
    {% endif %}
    <div class="panel-body">
    <h3>À propos</h3>
    {% if user.about %}
        {{ user.about | markdown }}
    {% else %}
        <em>Cet utilisateur n'a pas mis à jour sa description.</em>
    {% endif %}
    </div>
    <ul class="list-group">
        {% if user.name %}<li class="list-group-item"><span class="panel-list-title">Nom : </span>{{ user.name }}</li>{% endif %}
        {% if user.location %}<li class="list-group-item"><span class="panel-list-title">Emplacement : </span>{{ user.location }}</li>{% endif %}
        <li class="list-group-item"><span class="panel-list-title">Dernière connexion : </span>{{ moment(user.last_visit).fromNow() }}</li>
    </ul>
</div>
{% if current_user is equalto user %}
    <div class="btn-group-justified" style="width:100%">
        <a href="{{ url_for('articles.newarticle', category="post") }}" class="btn btn-default">Nouvel article</a>
        <a href="{{ url_for('articles.newarticle', category="image") }}" class="btn btn-default">Nouvelle image</a>
        <a href="{{ url_for('articles.newarticle', category="video") }}" class="btn btn-default">Nouveau vidéo</a>
    </div>
{% endif %}
<div class="page-header"><h1>Publications</h1></div>
<div class="text-center">{{ render_pagination(posts) }}</div>
{{ show_posts() }}
<div class="text-center">{{ render_pagination(posts) }}</div>
{%- endblock %}